/**
 * Static map of major gateway routes for discovery / docs.
 */
export function listRoutes() {
  return [
    { method: "GET", path: "/health", group: "ops", desc: "Liveness + stop auth/HMAC readiness" },
    { method: "GET", path: "/ready", group: "ops", desc: "Readiness (computer + queue + prod stop.ready)" },
    { method: "POST", path: "/stop", group: "ops", desc: "Kill-switch: abort sessions, drain WS/SSE" },
    { method: "POST", path: "/sessions/stop-all", group: "ops", desc: "Alias of POST /stop" },
    { method: "POST", path: "/xclaw/stop", group: "ops", desc: "Alias of POST /stop" },
    { method: "GET", path: "/metrics", group: "ops", desc: "Prometheus text metrics" },
    { method: "GET", path: "/version", group: "ops", desc: "Version + uptime" },
    { method: "GET", path: "/dashboard", group: "ops", desc: "Aggregated ops snapshot" },
    { method: "GET", path: "/report", group: "ops", desc: "Markdown status report" },
    { method: "GET", path: "/profile", group: "ops", desc: "Active deploy profile" },
    { method: "POST", path: "/config/reload", group: "ops", desc: "Soft config reload" },
    { method: "POST", path: "/agent/run", group: "agent", desc: "Run agent (JSON)" },
    { method: "POST", path: "/agent/run/stream", group: "agent", desc: "Run agent (SSE or NDJSON via Accept / ?format=ndjson)" },
    { method: "POST", path: "/jobs", group: "jobs", desc: "Run verified job" },
    { method: "GET", path: "/jobs", group: "jobs", desc: "Job history" },
    { method: "GET", path: "/queue", group: "queue", desc: "List queue + stats" },
    { method: "POST", path: "/queue", group: "queue", desc: "Enqueue job" },
    { method: "GET", path: "/queue/stats", group: "queue", desc: "Queue counts" },
    { method: "GET", path: "/queue/dead", group: "queue", desc: "Dead letter items" },
    { method: "POST", path: "/queue/pause", group: "queue", desc: "Pause worker" },
    { method: "POST", path: "/queue/resume", group: "queue", desc: "Resume worker" },
    { method: "POST", path: "/queue/clear", group: "queue", desc: "Clear terminal items" },
    { method: "POST", path: "/queue/retry-failed", group: "queue", desc: "Requeue failures" },
    { method: "GET", path: "/eval/baseline", group: "eval", desc: "Latest baseline JSON" },
    { method: "GET", path: "/eval/history", group: "eval", desc: "Eval run history" },
    { method: "GET", path: "/eval/spend", group: "eval", desc: "Spend rollup" },
    { method: "GET", path: "/eval/scoreboard", group: "eval", desc: "Autonomy KPI scoreboard" },
    { method: "GET", path: "/cron/eval", group: "eval", desc: "Eval cron status" },
    { method: "POST", path: "/cron/eval/run", group: "eval", desc: "Run eval suite now" },
    { method: "POST", path: "/channel/webchat/message", group: "chat", desc: "WebChat message" },
    { method: "POST", path: "/channel/webchat/message/stream", group: "chat", desc: "WebChat (SSE/NDJSON + Last-Event-ID resume)" },
    { method: "GET", path: "/chat/", group: "ui", desc: "WebChat UI" },
    { method: "GET", path: "/checkpoints", group: "jobs", desc: "List/load job checkpoints" },
    { method: "POST", path: "/checkpoints/resume", group: "jobs", desc: "Resume job from checkpoint" },
    { method: "POST", path: "/subagents/merge", group: "agent", desc: "Apply subagent worktree patch" },
    { method: "GET", path: "/security/pending", group: "security", desc: "Pending tool approvals" },
    { method: "POST", path: "/security/decide", group: "security", desc: "Approve/deny pending tool" },
    { method: "GET", path: "/approvals", group: "security", desc: "Alias: pending approvals" },
    { method: "POST", path: "/approvals/approve", group: "security", desc: "Approve pending tool" },
    { method: "POST", path: "/approvals/deny", group: "security", desc: "Deny pending tool" },
    { method: "GET", path: "/security/policy", group: "security", desc: "Approval policy info" },
    { method: "GET", path: "/memory", group: "memory", desc: "Durable workspace memory" },
    { method: "GET", path: "/control/", group: "ui", desc: "Control UI" },
    { method: "GET", path: "/xclaw/jwks.json", group: "auth", desc: "Public JWKS (verification keys)" },
    { method: "GET", path: "/.well-known/jwks.json", group: "auth", desc: "OIDC-style JWKS alias" },
    { method: "GET", path: "/jwks.json", group: "auth", desc: "JWKS short alias" },
    { method: "GET", path: "/xclaw/jwks/epoch", group: "auth", desc: "JWKS invalidation epoch" },
    { method: "POST", path: "/xclaw/jwks/invalidate", group: "auth", desc: "Publish/apply JWKS invalidation" },
    { method: "GET", path: "/xclaw/jwks/cache", group: "auth", desc: "JWKS cache status (auth)" },
    { method: "POST", path: "/swarm/run", group: "swarm", desc: "Start swarm fan-out / DAG run" },
    { method: "POST", path: "/swarm/run/stream", group: "swarm", desc: "Start swarm (SSE/NDJSON + Last-Event-ID resume)" },
    { method: "GET", path: "/swarm", group: "swarm", desc: "List swarm runs" },
    { method: "GET", path: "/swarm/:id", group: "swarm", desc: "Get swarm run by id" },
    { method: "GET", path: "/swarm/merges", group: "swarm", desc: "List merge proposals" },
    { method: "GET", path: "/swarm/merges/:id", group: "swarm", desc: "Get merge proposal" },
    { method: "POST", path: "/swarm/merges/:id/approve", group: "swarm", desc: "Approve merge proposal" },
    { method: "POST", path: "/swarm/merges/:id/reject", group: "swarm", desc: "Reject merge proposal" },
    { method: "GET", path: "/subagents", group: "swarm", desc: "List persisted subagents" },
    { method: "POST", path: "/api/swarm/goals", group: "swarm-ext", desc: "swarm-ext: submit goal (decompose→DAG→sub-agents→merge) — opt-in module" },
    { method: "POST", path: "/api/swarm/batch", group: "swarm-ext", desc: "swarm-ext: submit multiple goals" },
    { method: "GET", path: "/api/swarm/tasks/:id", group: "swarm-ext", desc: "swarm-ext: task status/result" },
    { method: "POST", path: "/api/swarm/tasks/:id/cancel", group: "swarm-ext", desc: "swarm-ext: cancel task" },
    { method: "GET", path: "/api/swarm/receipts/:taskId", group: "swarm-ext", desc: "swarm-ext: execution receipt" },
    { method: "GET", path: "/api/swarm/health", group: "swarm-ext", desc: "swarm-ext: module health (redis/plugins)" },
    { method: "GET", path: "/api/swarm/stats", group: "swarm-ext", desc: "swarm-ext: aggregate stats" },
    { method: "GET", path: "/api/swarm/sessions", group: "swarm-ext", desc: "swarm-ext: list sessions" },
    // MCP plane. POST /mcp runs the agent as an MCP server; /mcp/call invokes a
    // tool; POST /mcp/servers writes MCP config + stored credentials; /mcp/resources
    // reads resources and transcripts — all operator-only. The one exception is the
    // OAuth AS redirect (/mcp/oauth/callback), which is state-authenticated, not
    // token-authenticated, and is open-listed in gateway-route-coverage.test.mjs.
    { method: "POST", path: "/mcp", group: "mcp", desc: "MCP JSON-RPC — runs the agent as an MCP server" },
    { method: "GET", path: "/mcp/status", group: "mcp", desc: "Connected MCP server status" },
    { method: "GET", path: "/mcp/tools", group: "mcp", desc: "List tools from connected MCP servers" },
    { method: "POST", path: "/mcp/call", group: "mcp", desc: "Invoke a tool on a connected MCP server" },
    { method: "GET", path: "/mcp/servers", group: "mcp", desc: "List MCP servers (POST adds/writes config+creds, DELETE removes)" },
    { method: "POST", path: "/mcp/servers/test", group: "mcp", desc: "Test an MCP server definition" },
    { method: "GET", path: "/mcp/resources", group: "mcp", desc: "List MCP resources" },
    { method: "POST", path: "/mcp/resources/read", group: "mcp", desc: "Read an MCP resource" },
    { method: "GET", path: "/mcp/prompts", group: "mcp", desc: "List MCP prompts" },
    { method: "POST", path: "/mcp/prompts/get", group: "mcp", desc: "Get an MCP prompt" },
    { method: "POST", path: "/mcp/oauth/start", group: "mcp", desc: "Begin MCP OAuth authorization" },
    { method: "GET", path: "/mcp/oauth/callback", group: "mcp", desc: "MCP OAuth AS redirect (state-authenticated; open by design)" },
    { method: "POST", path: "/mcp/oauth/complete", group: "mcp", desc: "Complete MCP OAuth authorization" },
    { method: "GET", path: "/mcp/oauth/status", group: "mcp", desc: "MCP OAuth token status" },
    { method: "DELETE", path: "/mcp/oauth", group: "mcp", desc: "Revoke stored MCP OAuth tokens" },
    { method: "ALL", path: "/computer/proxy/*", group: "computer", desc: "Proxy to computer plane (single external port)" },
    { method: "ALL", path: "/xclaw/computer/*", group: "computer", desc: "Alias proxy to computer plane" },
  ];
}
