/**
 * Static map of major gateway routes for discovery / docs.
 */
export function listRoutes() {
  return [
    { method: "GET", path: "/health", group: "ops", desc: "Liveness" },
    { method: "GET", path: "/ready", group: "ops", desc: "Readiness (computer + queue depth)" },
    { method: "GET", path: "/metrics", group: "ops", desc: "Prometheus text metrics" },
    { method: "GET", path: "/version", group: "ops", desc: "Version + uptime" },
    { method: "GET", path: "/dashboard", group: "ops", desc: "Aggregated ops snapshot" },
    { method: "GET", path: "/report", group: "ops", desc: "Markdown status report" },
    { method: "GET", path: "/profile", group: "ops", desc: "Active deploy profile" },
    { method: "POST", path: "/config/reload", group: "ops", desc: "Soft config reload" },
    { method: "POST", path: "/agent/run", group: "agent", desc: "Run agent (JSON)" },
    { method: "POST", path: "/agent/run/stream", group: "agent", desc: "Run agent (SSE or NDJSON via Accept / ?format=ndjson)" },
    { method: "POST", path: "/jobs", group: "jobs", desc: "Run verified job" },
    { method: "GET", path: "/jobs", group: "jobs", desc: "Job history" },
    { method: "GET", path: "/queue", group: "queue", desc: "List queue + stats" },
    { method: "POST", path: "/queue", group: "queue", desc: "Enqueue job" },
    { method: "GET", path: "/queue/stats", group: "queue", desc: "Queue counts" },
    { method: "GET", path: "/queue/dead", group: "queue", desc: "Dead letter items" },
    { method: "POST", path: "/queue/pause", group: "queue", desc: "Pause worker" },
    { method: "POST", path: "/queue/resume", group: "queue", desc: "Resume worker" },
    { method: "POST", path: "/queue/clear", group: "queue", desc: "Clear terminal items" },
    { method: "POST", path: "/queue/retry-failed", group: "queue", desc: "Requeue failures" },
    { method: "GET", path: "/eval/baseline", group: "eval", desc: "Latest baseline JSON" },
    { method: "GET", path: "/eval/history", group: "eval", desc: "Eval run history" },
    { method: "GET", path: "/eval/spend", group: "eval", desc: "Spend rollup" },
    { method: "GET", path: "/eval/scoreboard", group: "eval", desc: "Autonomy KPI scoreboard" },
    { method: "GET", path: "/cron/eval", group: "eval", desc: "Eval cron status" },
    { method: "POST", path: "/cron/eval/run", group: "eval", desc: "Run eval suite now" },
    { method: "POST", path: "/channel/webchat/message", group: "chat", desc: "WebChat message" },
    { method: "POST", path: "/channel/webchat/message/stream", group: "chat", desc: "WebChat (SSE/NDJSON + Last-Event-ID resume)" },
    { method: "GET", path: "/chat/", group: "ui", desc: "WebChat UI" },
    { method: "GET", path: "/checkpoints", group: "jobs", desc: "List/load job checkpoints" },
    { method: "POST", path: "/checkpoints/resume", group: "jobs", desc: "Resume job from checkpoint" },
    { method: "POST", path: "/subagents/merge", group: "agent", desc: "Apply subagent worktree patch" },
    { method: "GET", path: "/security/pending", group: "security", desc: "Pending tool approvals" },
    { method: "POST", path: "/security/decide", group: "security", desc: "Approve/deny pending tool" },
    { method: "GET", path: "/security/policy", group: "security", desc: "Approval policy info" },
    { method: "GET", path: "/memory", group: "memory", desc: "Durable workspace memory" },
    { method: "GET", path: "/control/", group: "ui", desc: "Control UI" },
    { method: "GET", path: "/xclaw/jwks.json", group: "auth", desc: "Public JWKS (verification keys)" },
    { method: "GET", path: "/.well-known/jwks.json", group: "auth", desc: "OIDC-style JWKS alias" },
    { method: "GET", path: "/jwks.json", group: "auth", desc: "JWKS short alias" },
    { method: "GET", path: "/xclaw/jwks/epoch", group: "auth", desc: "JWKS invalidation epoch" },
    { method: "POST", path: "/xclaw/jwks/invalidate", group: "auth", desc: "Publish/apply JWKS invalidation" },
    { method: "GET", path: "/xclaw/jwks/cache", group: "auth", desc: "JWKS cache status (auth)" },
    { method: "POST", path: "/swarm/run", group: "swarm", desc: "Start swarm fan-out / DAG run" },
    { method: "POST", path: "/swarm/run/stream", group: "swarm", desc: "Start swarm (SSE/NDJSON + Last-Event-ID resume)" },
    { method: "GET", path: "/swarm", group: "swarm", desc: "List swarm runs" },
    { method: "GET", path: "/swarm/:id", group: "swarm", desc: "Get swarm run by id" },
    { method: "GET", path: "/swarm/merges", group: "swarm", desc: "List merge proposals" },
    { method: "GET", path: "/swarm/merges/:id", group: "swarm", desc: "Get merge proposal" },
    { method: "POST", path: "/swarm/merges/:id/approve", group: "swarm", desc: "Approve merge proposal" },
    { method: "POST", path: "/swarm/merges/:id/reject", group: "swarm", desc: "Reject merge proposal" },
    { method: "GET", path: "/subagents", group: "swarm", desc: "List persisted subagents" },
  ];
}
