/**
 * Static route catalog for GET /routes and docs.
 */
export function listRoutes() {
  return [
    { method: "GET", path: "/health", group: "ops", desc: "Gateway health" },
    { method: "GET", path: "/ready", group: "ops", desc: "Readiness" },
    { method: "GET", path: "/version", group: "ops", desc: "Version / uptime" },
    { method: "GET", path: "/metrics", group: "ops", desc: "Prometheus metrics" },
    { method: "GET", path: "/routes", group: "ops", desc: "This catalog" },
    { method: "GET", path: "/gateway/info", group: "ops", desc: "Gateway + computer status" },
    { method: "POST", path: "/agent/run", group: "agent", desc: "Run agent (JSON)" },
    { method: "POST", path: "/agent/run/stream", group: "agent", desc: "Run agent (SSE/NDJSON)" },
    { method: "GET", path: "/jobs", group: "jobs", desc: "List jobs" },
    { method: "POST", path: "/jobs", group: "jobs", desc: "Enqueue job" },
    { method: "GET", path: "/checkpoints", group: "jobs", desc: "List/load job checkpoints" },
    { method: "POST", path: "/checkpoints/resume", group: "jobs", desc: "Resume job from checkpoint" },
    { method: "POST", path: "/subagents/merge", group: "agent", desc: "Apply subagent worktree patch" },
    { method: "GET", path: "/security/pending", group: "security", desc: "Pending tool approvals" },
    { method: "POST", path: "/security/decide", group: "security", desc: "Approve/deny pending tool" },
    { method: "GET", path: "/approvals", group: "security", desc: "Alias: pending approvals" },
    { method: "POST", path: "/approvals/approve", group: "security", desc: "Approve pending tool" },
    { method: "POST", path: "/approvals/deny", group: "security", desc: "Deny pending tool" },
    { method: "GET", path: "/security/policy", group: "security", desc: "Approval policy info" },
    { method: "GET", path: "/memory", group: "memory", desc: "Durable workspace memory" },
    { method: "GET", path: "/control/", group: "ui", desc: "Control UI" },
    { method: "GET", path: "/xclaw/jwks.json", group: "auth", desc: "Public JWKS (verification keys)" },
    { method: "GET", path: "/.well-known/jwks.json", group: "auth", desc: "OIDC-style JWKS alias" },
    { method: "GET", path: "/jwks.json", group: "auth", desc: "JWKS short alias" },
    { method: "GET", path: "/xclaw/jwks/epoch", group: "auth", desc: "JWKS invalidation epoch" },
    { method: "POST", path: "/xclaw/jwks/invalidate", group: "auth", desc: "Publish/apply JWKS invalidation" },
    { method: "GET", path: "/xclaw/jwks/cache", group: "auth", desc: "JWKS cache status (auth)" },
    { method: "POST", path: "/swarm/run", group: "swarm", desc: "Start swarm fan-out / DAG run" },
    { method: "POST", path: "/swarm/run/stream", group: "swarm", desc: "Start swarm (SSE/NDJSON + Last-Event-ID resume)" },
    { method: "GET", path: "/swarm", group: "swarm", desc: "List swarm runs" },
    { method: "GET", path: "/swarm/:id", group: "swarm", desc: "Get swarm run by id" },
    { method: "GET", path: "/swarm/merges", group: "swarm", desc: "List merge proposals" },
    { method: "GET", path: "/swarm/merges/:id", group: "swarm", desc: "Get merge proposal" },
    { method: "POST", path: "/swarm/merges/:id/approve", group: "swarm", desc: "Approve merge proposal" },
    { method: "POST", path: "/swarm/merges/:id/reject", group: "swarm", desc: "Reject merge proposal" },
    { method: "GET", path: "/subagents", group: "swarm", desc: "List persisted subagents" },
    { method: "ALL", path: "/computer/proxy/*", group: "computer", desc: "Proxy to computer plane (single external port)" },
    { method: "ALL", path: "/xclaw/computer/*", group: "computer", desc: "Alias proxy to computer plane" },
  ];
}
